---
title: "Intro To R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# put all packages that you require here
require(data.table)
require(ggplot2)
require(Lahman)
```


```{r}
### Looking at Clint Hurdle's baseball card, create 2 vectors with K for 
### number of strikeouts in a season, and BB for number of walks:
K <- c(7,84,24,61,10,6,10,20)
BB <- c(2,56,28,34,13,2,2,13)


### Can use seq() function to generate a vector of numbers easily,
### will do so for the years Hurdle played:
Year <- c(seq(1977,1983,by=1), 1985)

### Can also calculate Hurdle's age during these years given birth
### date on back of card as 1957:
Age <- Year - 1957

### Ability to do element-by-element calculations w/ vectors,
### such as finding Hurdle's K:BB ratio:
KBB.ratio <- K/BB

plot(Age,KBB.ratio,main="PLOT")
lines(Age,KBB.ratio,col="goldenrod")

### Can find which year/age Hurdle's K:BB ratio < 1:
i <- which(KBB.ratio < 1)
Year[i]
Age[i]
Year[KBB.ratio<1]
Age[KBB.ratio<1]
```




```{r}
#################
### More examples:
#################

x<-c(1,3,5,7,9)
x
x[2]
x[2:3]
x[c(1,4)]

length(x)

x<-c(2,3)
y<-c(4,5)
x+y


x <- c(6,5,4,3,2)
y <- c(8,7,5,3,1)

m1 <- rbind(x,y)
m2 <- cbind(x,y)

m1
m1[1,1]
m1[,4]
m3 <- m1 %*% m2
t(m1)
solve(m3)
dim(m2)
```


## types/classes

## logical/aggregate operators
```{r}
### If using csv:
#   Batting <- read.csv("Batting.csv")

### From package:
data(Batting)
head(Batting)

### WHO HIT THE MOST HOME RUNS IN THE '40S?

### Use the subset function to select batting data only 
### for seasons between 1940 and 1949, store in new data frame:
batting <- as.data.table(Batting)
Batting.40 <- subset(Batting, yearID >= 1940 & yearID <= 1949)
batting[yearID >= 1940 & yearID <= 1949][order(-HR)]

ggplot(batting, aes(x = yearID, fill = lgID)) +
  geom_histogram()

ggplot(batting[yearID >= 2000 & yearID <= 2010], aes(x = SO, y = BB)) + 
  geom_point() +
  geom_smooth(method = lm) + 
  labs(x = "Strikeouts",
       y = "Walks",
       title = "Strikeout vs. Walks in 2000-2010")

ggplot(batting[yearID>= 1940 & yearID <= 1950, sum(HR), by = yearID], aes(x = yearID, y = V1)) +
  geom_bar(stat = "identity")

```


```{r}
### sapply function is useful for repeating an operation over 
### values in a vector

### Here we are interested in computing the total number of homeruns
### for each player in the Batting.40 data frame.

### First need to define a function compute.hr that computes the total
### HR for a player with playerID equal to pid:

compute.hr <- function(pid,batting=Batting.40) {
  d <- subset(batting, playerID == pid)
  return(sum(d$HR))
}
```

### SPLITTING, APPLYING, AND COMBINING DATA
```{r}
### With the unique() function, can get a vector of all the player
### ids in the 1940s, then use sapply with compute.hr over this vector to calculate
### the number of HRs for each unique player.  The output is a vector
### with the total HR count for each player:

players <- unique(Batting.40$playerID)


HRcounts <- sapply(players,compute.hr)

### Much faster with plyr, plus no setup needed!
library(plyr)
HRply <- ddply(Batting.40, .(playerID), summarize, hr=sum(HR))

### Can view the first couple with head:
head(HRcounts)
```

```{r}
### With the unique() function, can get a vector of all the player
### ids in the 1940s, then use sapply with compute.hr over this vector to calculate
### the number of HRs for each unique player.  The output is a vector
### with the total HR count for each player:

players <- unique(Batting.40$playerID)


HRcounts <- sapply(players,compute.hr)

### Much faster with plyr, plus no setup needed!
library(plyr)
HRply <- ddply(Batting.40, .(playerID), summarize, hr=sum(HR))

### Can view the first couple with head:
head(HRcounts)
```

```{r}
### Can create a new data frame with the data.frame function,
### with two vars in the data frame - Player corresponding to the 
### player ids and HR for HR counts.

### Can also use order() function to sort data frame so the 
### best HR hitters are on the top:

homerun.40 <- data.frame(Player=players, HR=HRcounts)
homerun.40 <- homerun.40[order(homerun.40$HR, decreasing=TRUE),]
head(homerun.40)

### Want the names of these players:
help(Master)
### In the Master sheet:
data(Master)
```

```{r}


### Can find which the row indices of the players in our HR data frame
### by using the which() function.

### First example of the first player:
first <- which(homerun.40$Player[1] == Master$playerID)
### Then using with() can specify a data frame, don't
### have to keep typing $ symbols.
### Print of course displays.
### Paste combine multiple strings into one:
with(Master,print(paste(nameFirst[first],nameLast[first],sep=" ")))
```

```{r}

### How do I wrap this into a function?

findplayername <- function(pid,df=Master){
  index <- which(pid == df$playerID)
  return(with(df,paste(nameFirst[index],nameLast[index],sep=" ")))
}

```

```{r}
### Now use sapply to retrieve all names and assign this to a 
### new column in the data frame:
homerun.40$Full_Name <- sapply(homerun.40$Player,findplayername)
head(homerun.40)
homerun.40[homerun.40$Full_Name=="Jackie Robinson",]
################################
################################

```

```{r}
# build a model to predict H:
 
 
# let's explore ABs and Hits:
 
# start with some data summaries:
 
# create rounded ABs:
library(tidyverse)
library(dplyr)
library(dataframes2xls)

df <- data.frame(Batting)

df %>%
  filter(yearID > 1970) %>%
  mutate(ab.r = round((AB / 10),0)*10) %>%
  group_by(ab.r) %>%
  summarize(mn.H = mean(H, na.rm = TRUE)) %>%
  ggplot(.,aes(x = ab.r, y = mn.H)) +
  geom_point()
 
df.sub = df %>%
  filter(AB > 50) %>%
  filter(IBB > 3)
 
# let's make a simple linear model, using ABs
# to predict H:

ggplot(df, aes(x = AB, y = H)) +
  geom_point()

lm.1 = lm(H ~ AB, data = df)
lm.2 = lm(HR ~ IBB, data = df.sub)
 
summary(lm.1)
summary(lm.2)
 
df %>%
  filter(yearID > 1970) %>%
  ggplot(.,aes(x = IBB, y = HR)) +
  geom_point()

df %>%
  filter(yearID > 1970) %>%
  ggplot(.,aes(x = SB, y = CS)) +
  geom_point()

df.sub = df %>%
  filter(SB > 5) %>%
  filter(CS > 3)

lm.3 = lm(CS ~ SB, data = df.sub)
summary(lm.3)
head(Batting)
```



